server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL}/eureka

security:
  oauth2:
    resource:
      jwt:
        key-value: 123

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: authentication-service
          uri: http://${AUTHENTICATION_SERVICE_URL:localhost}:${AUTHENTICATION_SERVICE_PORT:8082}
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service/(?<remaining>.*), /${remaining}
        - id: challenges-service
          uri: http://${CHALLENGES_SERVICE_URL:localhost}:${CHALLENGES_SERVICE_PORT:8083}
          predicates:
            - Path=/challenges-service/**
          filters:
            - RewritePath=/challenges-service/(?<remaining>.*), /${remaining}
        - id: team-service
          uri: http://${TEAM_SERVICE_URL:localhost}:${TEAM_SERVICE_PORT:8084}
          predicates:
            - Path=/team-service/**
          filters:
            - RewritePath=/team-service/(?<remaining>.*), /${remaining}
        - id: user-service
          uri: http://${USER_SERVICE_URL:localhost}:${USER_SERVICE_PORT:8085}
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remaining>.*), /${remaining}